# Generated by Django 5.1.4 on 2024-12-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='telefon',
            field=models.PositiveIntegerField(),
        ),
    ]
