# Generated by Django 5.1.4 on 2024-12-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_telefon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='telefon',
        ),
        migrations.AddField(
            model_name='students',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
