# Generated by Django 5.1.4 on 2024-12-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_students_telefon_students_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='rasm',
        ),
    ]
