# Generated by Django 5.1.4 on 2024-12-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_students_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='manzil',
            field=models.CharField(default='Adress mavjud emas', max_length=300),
        ),
        migrations.AddField(
            model_name='students',
            name='rasm',
            field=models.ImageField(default='images/default.jpg', upload_to='student_image/'),
        ),
        migrations.AddField(
            model_name='students',
            name='telefon',
            field=models.CharField(default='+998 99 999 99 99', max_length=13),
        ),
    ]
