# Generated by Django 5.1.4 on 2024-12-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_students_manzil_students_rasm_students_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='manzil',
            field=models.TextField(),
        ),
    ]
