# Generated by Django 5.1.4 on 2025-01-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_bolalar_alter_group_sinf'),
        ('students', '0006_alter_students_manzil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='guruh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.group'),
        ),
    ]
