# Generated by Django 5.1.4 on 2024-12-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('fan', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ish', models.PositiveIntegerField()),
                ('rasm', models.ImageField(upload_to='teachers_image/')),
            ],
        ),
    ]
