# Generated by Django 5.1.4 on 2024-12-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('sinf', models.CharField(max_length=50)),
                ('bolalar', models.CharField(max_length=50)),
            ],
        ),
    ]
