# Generated by Django 5.1.4 on 2025-01-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='bolalar',
        ),
        migrations.AlterField(
            model_name='group',
            name='sinf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sinf', to='teachers.teachers'),
        ),
    ]
