# Generated by Django 5.1.4 on 2025-01-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='rahbar',
        ),
    ]
